openapi: 3.0.0
info:
  title: Check In API
  version: 0.1.0
  description: Check In API for Aetheras Employees
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /:
    get:
      responses:
        200:
          description: OK
